name: itaku_api
description: Dart wrapper for the Itaku web API
version: 1.0.0
repository: https://github.com/entriphy/dart_itaku_api

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  dio: ^5.3.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
